// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbaosbmpasflazdxrmam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiYW9zYm1wYXNmbGF6ZHhybWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzg2NjYsImV4cCI6MjA1NjkxNDY2Nn0.1DzNC4YV49AUGWYHzPR0UQak5PyRMDwZ7mmWwgtfdMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);